# Generated by Django 3.1.2 on 2021-01-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_remove_shelterhome_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(db_index=True, default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('dob', models.DateField()),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('aadhaar_number', models.CharField(blank=True, max_length=150, null=True)),
                ('last_date_of_cwc_order_or_review', models.DateField(blank=True, null=True)),
                ('cwc_started_the_process_of_declaring', models.DateField(blank=True, null=True)),
                ('cwc_order_number', models.CharField(blank=True, max_length=150, null=True)),
                ('flagging_status', models.IntegerField(blank=True, choices=[(1, 'Pending Adoption'), (2, 'Ready for Adoption')], default=1, null=True)),
                ('child_classification', models.ManyToManyField(to='master_data.ChildClassification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(db_index=True, default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=150)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='child_management.child')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.relationship')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(db_index=True, default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('date_of_visit', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='child_management.child')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='child_management.guardian')),
            ],
            options={
                'verbose_name_plural': 'Family Visit',
            },
        ),
        migrations.CreateModel(
            name='ChildShelterhomeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(db_index=True, default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('admission_number', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='child_management.child')),
                ('shelter_home', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.shelterhome')),
            ],
            options={
                'verbose_name_plural': 'Child Shelterhome Relation',
            },
        ),
    ]
