# Generated by Django 3.1.2 on 2021-01-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Child'},
        ),
        migrations.AlterModelOptions(
            name='childshelterhomerelation',
            options={'verbose_name_plural': 'Child with Shelter Home Relation'},
        ),
        migrations.AlterModelOptions(
            name='familyvisit',
            options={'verbose_name_plural': 'Family Visit Tracking'},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name_plural': 'Guardian'},
        ),
    ]
