# Generated by Django 3.1.2 on 2021-01-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0002_auto_20210108_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='case_number',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
