# Generated by Django 3.1.2 on 2021-01-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0004_auto_20210127_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildFlaggedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], db_index=True, default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('flagged_date', models.DateField()),
                ('reason_for_flagging', models.TextField()),
                ('flagged_status', models.IntegerField(blank=True, choices=[(1, 'Pending Adoption'), (2, 'Ready for Adoption')], default=1, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='child_management.child')),
            ],
            options={
                'verbose_name_plural': 'Child Flagged History',
            },
        ),
    ]
