# Generated by Django 3.1.2 on 2021-01-29 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0005_childflaggedhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images/child/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images/guardian/'),
            preserve_default=False,
        ),
    ]
