# Generated by Django 3.1.2 on 2021-02-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0006_auto_20210129_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='image',
            field=models.ImageField(upload_to='child/'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='image',
            field=models.ImageField(upload_to='guardian/'),
        ),
    ]
