# Generated by Django 3.1.2 on 2021-02-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_auto_20210209_0710'),
        ('child_management', '0010_child_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='flagging_status',
        ),
        migrations.AlterField(
            model_name='child',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='child/'),
        ),
        migrations.AlterField(
            model_name='childcwchistory',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_management.child'),
        ),
        migrations.AlterField(
            model_name='childflaggedhistory',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_management.child'),
        ),
        migrations.AlterField(
            model_name='childflaggedhistory',
            name='flagged_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Child recommended for adoption enquiry'), (2, 'Legally free for adoption'), (3, 'Not applicable')], null=True),
        ),
        migrations.AlterField(
            model_name='childshelterhomerelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_management.child'),
        ),
        migrations.AlterField(
            model_name='childshelterhomerelation',
            name='shelter_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.shelterhome'),
        ),
        migrations.AlterField(
            model_name='familyvisit',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_management.child'),
        ),
        migrations.AlterField(
            model_name='familyvisit',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_management.guardian'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_management.child'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guardian/'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.relationship'),
        ),
    ]
