# Generated by Django 3.1.2 on 2021-08-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_management', '0019_auto_20210317_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childshelterhomerelation',
            name='date_of_admission',
            field=models.DateField(),
        ),
    ]
