# Generated by Django 3.1.2 on 2021-01-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_remove_shelterhome_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centre',
            options={'verbose_name_plural': 'Centre'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'District'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name_plural': 'Relationship'},
        ),
        migrations.AlterModelOptions(
            name='shelterhome',
            options={'verbose_name_plural': 'Shelter Homes'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'State/UTs'},
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
