# Generated by Django 3.1.2 on 2021-01-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_userlocationrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='childclassification',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='district',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='shelterhome',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='userlocationrelation',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], db_index=True, default=2),
        ),
    ]
