# Generated by Django 3.1.2 on 2021-01-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='childclassification',
            name='use_for_flagging',
            field=models.BooleanField(default=False),
        ),
    ]
