# Generated by Django 3.1.2 on 2021-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_childclassification_use_for_flagging'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterhome',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shelterhome',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
