# Generated by Django 3.1.2 on 2021-02-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_auto_20210203_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='disclaimer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
