# Generated by Django 3.1.2 on 2021-02-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_config_disclaimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'No'), (2, 'Yes')], db_index=True, default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('chart_type', models.IntegerField(blank=True, help_text='1=Column Chart, 2=Pie Chart, 3=Table Chart', null=True)),
                ('chart_name', models.CharField(blank=True, max_length=500, null=True)),
                ('chart_title', models.CharField(blank=True, max_length=500, null=True)),
                ('vertical_axis_title', models.CharField(blank=True, max_length=200, null=True)),
                ('horizontal_axis_title', models.CharField(blank=True, max_length=200, null=True)),
                ('chart_note', models.TextField(blank=True, null=True)),
                ('chart_tooltip', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Chart Meta',
            },
        ),
    ]
