# Generated by Django 3.1.2 on 2021-02-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_chartmeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='disclaimer',
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
