# Generated by Django 3.1.2 on 2021-02-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0013_auto_20210209_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.state'),
        ),
        migrations.AlterField(
            model_name='shelterhome',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.district'),
        ),
        migrations.AlterField(
            model_name='state',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.centre'),
        ),
        migrations.AlterField(
            model_name='userlocationrelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='userlocationrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
